import adapter from '@sveltejs/adapter-static';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: adapter({
			pages: 'build',
			assets: 'build',
			fallback: 'index.html'
		}),
		prerender: {
			handleHttpError({ path, message }) {
				// PWA icons are generated by vite-plugin-pwa, not present during prerender
				if (path.startsWith('/pwa-')) return 'warn';
				throw new Error(message);
			}
		}
	}
};

export default config;
